module app.models {
    "use strict";

    export class IndiaCPProgram {
        /**
         * Unique identifier representing a specific CP Program raised by an Issuer
         */
        "programId"?: string;

        /**
         * Name of the CP Program
         */
        "name"?: string;

        /**
         * User identifier
         */
        "userId"?: string;

        /**
         * Type of the CP Program
         */
        "type"?: string;

        /**
         * Purpose of the CP Program
         */
        "purpose"?: string;

        /**
         * Unique CP Security Identifier No. In India this is issued by NSDL for Commercial Paper type of securities.
         */
        "isin"?: string;

        /**
         * Unique identifier of the Issuer. This will also uniquely map to the DL Node of the Issuer
         */
        "issuerId"?: string;

        /**
         * Display name of the Issuer
         */
        "issuerName"?: string;

        /**
         * Date when the CP Program was initiated. India regulations mandate that a program should be fully allocated within 2 weeks of commencement.
         */
        "issueCommencementDate"?: Date;

        /**
         * Total borrowing amount under this CP Program
         */
        "programSize"?: number;

        /**
         * Amount already allocated to the CP program
         */
        "programAllocatedValue"?: number;

        /**
         * Currency of the issue of CP notes
         */
        "programCurrency"?: string;

        /**
         * No of days to maturity from the value date
         */
        "maturityDays"?: number;

        /**
         * Unique identifier of the IPA. This will also uniquely map to the DL Node of the IPA
         */
        "ipaId"?: string;

        /**
         * Display name of the IPA
         */
        "ipaName"?: string;

        /**
         * Unique identifier of the Depository (NSDL). This will also uniquely map to the DL Node of the Depository
         */
        "depositoryId"?: string;

        /**
         * Display name of the Depository
         */
        "depositoryName"?: string;

        /**
         * Unique identifier of the documents sent to the depository to generate ISIN
         */
        "isinGenerationRequestDocId"?: string;

        /**
         * Unique identifier of the documents sent to the IPA to certify the CP Program
         */
        "ipaVerificationRequestDocId"?: string;

        /**
         * Unique identifier of the IPA certificate issued by the IPA on verification of the CP Program and supporting Issuer documents
         */
        "ipaCertificateDocId"?: string;

        /**
         * Unique identifier of the Corporate Action Form generated by the Issuer to allot CP
         */
        "corporateActionFormDocId"?: string;

        /**
         * Unique identifier of the Allotment Letter generated by IPA for CP transfer to Investor DP account
         */
        "allotmentLetterDocId"?: string;

        /**
         * Top level organizational borrowing limit contract
         */
        "orgUnit"?: string;

        /**
         * Current status of the CP Program
         */
        "status"?: string;

        /**
         * Current version of the CP Program
         */
        "version"?: number;

        /**
         * Unique identifier of the Logged-in User that performed the action. This is required for Audit History
         */
        "modifiedBy"?: string;

        /**
         * Last Modified Date for this CPIssue. This is required for Audit History
         */
        "lastModified"?: Date;

}}