/*
 * IndiaCP API
 * This API will drive the UI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.barclays.indiacp.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;

/**
 * CPProgram
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-12-22T06:22:33.818Z")
public class CPProgram   {
  @JsonProperty("program_id")
  private String programId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("purpose")
  private String purpose = null;

  @JsonProperty("issuer_id")
  private String issuerId = null;

  @JsonProperty("issuer_name")
  private String issuerName = null;

  @JsonProperty("issue_commencement_date")
  private Date issueCommencementDate = null;

  @JsonProperty("program_size")
  private Integer programSize = null;

  @JsonProperty("program_allocated_value")
  private Double programAllocatedValue = null;

  @JsonProperty("program_currency")
  private String programCurrency = null;

  @JsonProperty("maturity_days")
  private Integer maturityDays = null;

  @JsonProperty("ipa_id")
  private String ipaId = null;

  @JsonProperty("ipa_name")
  private String ipaName = null;

  @JsonProperty("depository_id")
  private String depositoryId = null;

  @JsonProperty("depository_name")
  private String depositoryName = null;

  @JsonProperty("isin_generation_request_doc_id")
  private String isinGenerationRequestDocId = null;

  @JsonProperty("ipa_verification_request_doc_id")
  private String ipaVerificationRequestDocId = null;

  @JsonProperty("ipa_certificate_doc_id")
  private String ipaCertificateDocId = null;

  @JsonProperty("corporate_action_form_doc_id")
  private String corporateActionFormDocId = null;

  @JsonProperty("allotment_letter_doc_id")
  private String allotmentLetterDocId = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("last_modified")
  private Date lastModified = null;

  public CPProgram programId(String programId) {
    this.programId = programId;
    return this;
  }

   /**
   * Unique identifier representing a specific CP Program raised by an Issuer
   * @return programId
  **/
  //@ApiModelProperty(value = "Unique identifier representing a specific CP Program raised by an Issuer")
  public String getProgramId() {
    return programId;
  }

  public void setProgramId(String programId) {
    this.programId = programId;
  }

  public CPProgram name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the CP Program
   * @return name
  **/
  //@ApiModelProperty(value = "Name of the CP Program")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CPProgram type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the CP Program
   * @return type
  **/
  //@ApiModelProperty(value = "Type of the CP Program")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CPProgram purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * Purpose of the CP Program
   * @return purpose
  **/
  //@ApiModelProperty(value = "Purpose of the CP Program")
  public String getPurpose() {
    return purpose;
  }

  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public CPProgram issuerId(String issuerId) {
    this.issuerId = issuerId;
    return this;
  }

   /**
   * Unique identifier of the Issuer. This will also uniquely map to the DL Node of the Issuer
   * @return issuerId
  **/
  //@ApiModelProperty(value = "Unique identifier of the Issuer. This will also uniquely map to the DL Node of the Issuer")
  public String getIssuerId() {
    return issuerId;
  }

  public void setIssuerId(String issuerId) {
    this.issuerId = issuerId;
  }

  public CPProgram issuerName(String issuerName) {
    this.issuerName = issuerName;
    return this;
  }

   /**
   * Display name of the Issuer
   * @return issuerName
  **/
  //@ApiModelProperty(value = "Display name of the Issuer")
  public String getIssuerName() {
    return issuerName;
  }

  public void setIssuerName(String issuerName) {
    this.issuerName = issuerName;
  }

  public CPProgram issueCommencementDate(Date issueCommencementDate) {
    this.issueCommencementDate = issueCommencementDate;
    return this;
  }

   /**
   * Date when the CP Program was initiated. India regulations mandate that a program should be fully allocated within 2 weeks of commencement.
   * @return issueCommencementDate
  **/
  //@ApiModelProperty(value = "Date when the CP Program was initiated. India regulations mandate that a program should be fully allocated within 2 weeks of commencement.")
  public Date getIssueCommencementDate() {
    return issueCommencementDate;
  }

  public void setIssueCommencementDate(Date issueCommencementDate) {
    this.issueCommencementDate = issueCommencementDate;
  }

  public CPProgram programSize(Integer programSize) {
    this.programSize = programSize;
    return this;
  }

   /**
   * Total borrowing amount under this CP Program
   * @return programSize
  **/
  //@ApiModelProperty(value = "Total borrowing amount under this CP Program")
  public Integer getProgramSize() {
    return programSize;
  }

  public void setProgramSize(Integer programSize) {
    this.programSize = programSize;
  }

  public CPProgram programAllocatedValue(Double programAllocatedValue) {
    this.programAllocatedValue = programAllocatedValue;
    return this;
  }

   /**
   * Amount already allocated to the CP program
   * @return programAllocatedValue
  **/
  //@ApiModelProperty(value = "Amount already allocated to the CP program")
  public Double getProgramAllocatedValue() {
    return programAllocatedValue;
  }

  public void setProgramAllocatedValue(Double programAllocatedValue) {
    this.programAllocatedValue = programAllocatedValue;
  }

  public CPProgram programCurrency(String programCurrency) {
    this.programCurrency = programCurrency;
    return this;
  }

   /**
   * Currency of the issue of CP notes
   * @return programCurrency
  **/
  //@ApiModelProperty(value = "Currency of the issue of CP notes")
  public String getProgramCurrency() {
    return programCurrency;
  }

  public void setProgramCurrency(String programCurrency) {
    this.programCurrency = programCurrency;
  }

  public CPProgram maturityDays(Integer maturityDays) {
    this.maturityDays = maturityDays;
    return this;
  }

   /**
   * No of days to maturity from the value date
   * @return maturityDays
  **/
  //@ApiModelProperty(value = "No of days to maturity from the value date")
  public Integer getMaturityDays() {
    return maturityDays;
  }

  public void setMaturityDays(Integer maturityDays) {
    this.maturityDays = maturityDays;
  }

  public CPProgram ipaId(String ipaId) {
    this.ipaId = ipaId;
    return this;
  }

   /**
   * Unique identifier of the IPA. This will also uniquely map to the DL Node of the IPA
   * @return ipaId
  **/
  //@ApiModelProperty(value = "Unique identifier of the IPA. This will also uniquely map to the DL Node of the IPA")
  public String getIpaId() {
    return ipaId;
  }

  public void setIpaId(String ipaId) {
    this.ipaId = ipaId;
  }

  public CPProgram ipaName(String ipaName) {
    this.ipaName = ipaName;
    return this;
  }

   /**
   * Display name of the IPA
   * @return ipaName
  **/
  //@ApiModelProperty(value = "Display name of the IPA")
  public String getIpaName() {
    return ipaName;
  }

  public void setIpaName(String ipaName) {
    this.ipaName = ipaName;
  }

  public CPProgram depositoryId(String depositoryId) {
    this.depositoryId = depositoryId;
    return this;
  }

   /**
   * Unique identifier of the Depository (NSDL). This will also uniquely map to the DL Node of the Depository
   * @return depositoryId
  **/
  //@ApiModelProperty(value = "Unique identifier of the Depository (NSDL). This will also uniquely map to the DL Node of the Depository")
  public String getDepositoryId() {
    return depositoryId;
  }

  public void setDepositoryId(String depositoryId) {
    this.depositoryId = depositoryId;
  }

  public CPProgram depositoryName(String depositoryName) {
    this.depositoryName = depositoryName;
    return this;
  }

   /**
   * Display name of the Depository
   * @return depositoryName
  **/
  //@ApiModelProperty(value = "Display name of the Depository")
  public String getDepositoryName() {
    return depositoryName;
  }

  public void setDepositoryName(String depositoryName) {
    this.depositoryName = depositoryName;
  }

  public CPProgram isinGenerationRequestDocId(String isinGenerationRequestDocId) {
    this.isinGenerationRequestDocId = isinGenerationRequestDocId;
    return this;
  }

   /**
   * Unique identifier of the documents sent to the depository to generate ISIN
   * @return isinGenerationRequestDocId
  **/
  //@ApiModelProperty(value = "Unique identifier of the documents sent to the depository to generate ISIN")
  public String getIsinGenerationRequestDocId() {
    return isinGenerationRequestDocId;
  }

  public void setIsinGenerationRequestDocId(String isinGenerationRequestDocId) {
    this.isinGenerationRequestDocId = isinGenerationRequestDocId;
  }

  public CPProgram ipaVerificationRequestDocId(String ipaVerificationRequestDocId) {
    this.ipaVerificationRequestDocId = ipaVerificationRequestDocId;
    return this;
  }

   /**
   * Unique identifier of the documents sent to the IPA to certify the CP Program
   * @return ipaVerificationRequestDocId
  **/
  //@ApiModelProperty(value = "Unique identifier of the documents sent to the IPA to certify the CP Program")
  public String getIpaVerificationRequestDocId() {
    return ipaVerificationRequestDocId;
  }

  public void setIpaVerificationRequestDocId(String ipaVerificationRequestDocId) {
    this.ipaVerificationRequestDocId = ipaVerificationRequestDocId;
  }

  public CPProgram ipaCertificateDocId(String ipaCertificateDocId) {
    this.ipaCertificateDocId = ipaCertificateDocId;
    return this;
  }

   /**
   * Unique identifier of the IPA certificate issued by the IPA on verification of the CP Program and supporting Issuer documents
   * @return ipaCertificateDocId
  **/
  //@ApiModelProperty(value = "Unique identifier of the IPA certificate issued by the IPA on verification of the CP Program and supporting Issuer documents")
  public String getIpaCertificateDocId() {
    return ipaCertificateDocId;
  }

  public void setIpaCertificateDocId(String ipaCertificateDocId) {
    this.ipaCertificateDocId = ipaCertificateDocId;
  }

  public CPProgram corporateActionFormDocId(String corporateActionFormDocId) {
    this.corporateActionFormDocId = corporateActionFormDocId;
    return this;
  }

   /**
   * Unique identifier of the Corporate Action Form generated by the Issuer to allot CP
   * @return corporateActionFormDocId
  **/
  //@ApiModelProperty(value = "Unique identifier of the Corporate Action Form generated by the Issuer to allot CP")
  public String getCorporateActionFormDocId() {
    return corporateActionFormDocId;
  }

  public void setCorporateActionFormDocId(String corporateActionFormDocId) {
    this.corporateActionFormDocId = corporateActionFormDocId;
  }

  public CPProgram allotmentLetterDocId(String allotmentLetterDocId) {
    this.allotmentLetterDocId = allotmentLetterDocId;
    return this;
  }

   /**
   * Unique identifier of the Allotment Letter generated by IPA for CP transfer to Investor DP account
   * @return allotmentLetterDocId
  **/
  //@ApiModelProperty(value = "Unique identifier of the Allotment Letter generated by IPA for CP transfer to Investor DP account")
  public String getAllotmentLetterDocId() {
    return allotmentLetterDocId;
  }

  public void setAllotmentLetterDocId(String allotmentLetterDocId) {
    this.allotmentLetterDocId = allotmentLetterDocId;
  }

  public CPProgram status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Current status of the CP Program
   * @return status
  **/
  //@ApiModelProperty(value = "Current status of the CP Program")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CPProgram version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Current version of the CP Program
   * @return version
  **/
  //@ApiModelProperty(value = "Current version of the CP Program")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public CPProgram lastModified(Date lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Unique identifier of the Allotment Letter generated by IPA for CP transfer to Investor DP account
   * @return lastModified
  **/
  //@ApiModelProperty(value = "Unique identifier of the Allotment Letter generated by IPA for CP transfer to Investor DP account")
  public Date getLastModified() {
    return lastModified;
  }

  public void setLastModified(Date lastModified) {
    this.lastModified = lastModified;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CPProgram cpProgram = (CPProgram) o;
    return Objects.equals(this.programId, cpProgram.programId) &&
        Objects.equals(this.name, cpProgram.name) &&
        Objects.equals(this.type, cpProgram.type) &&
        Objects.equals(this.purpose, cpProgram.purpose) &&
        Objects.equals(this.issuerId, cpProgram.issuerId) &&
        Objects.equals(this.issuerName, cpProgram.issuerName) &&
        Objects.equals(this.issueCommencementDate, cpProgram.issueCommencementDate) &&
        Objects.equals(this.programSize, cpProgram.programSize) &&
        Objects.equals(this.programAllocatedValue, cpProgram.programAllocatedValue) &&
        Objects.equals(this.programCurrency, cpProgram.programCurrency) &&
        Objects.equals(this.maturityDays, cpProgram.maturityDays) &&
        Objects.equals(this.ipaId, cpProgram.ipaId) &&
        Objects.equals(this.ipaName, cpProgram.ipaName) &&
        Objects.equals(this.depositoryId, cpProgram.depositoryId) &&
        Objects.equals(this.depositoryName, cpProgram.depositoryName) &&
        Objects.equals(this.isinGenerationRequestDocId, cpProgram.isinGenerationRequestDocId) &&
        Objects.equals(this.ipaVerificationRequestDocId, cpProgram.ipaVerificationRequestDocId) &&
        Objects.equals(this.ipaCertificateDocId, cpProgram.ipaCertificateDocId) &&
        Objects.equals(this.corporateActionFormDocId, cpProgram.corporateActionFormDocId) &&
        Objects.equals(this.allotmentLetterDocId, cpProgram.allotmentLetterDocId) &&
        Objects.equals(this.status, cpProgram.status) &&
        Objects.equals(this.version, cpProgram.version) &&
        Objects.equals(this.lastModified, cpProgram.lastModified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(programId, name, type, purpose, issuerId, issuerName, issueCommencementDate, programSize, programAllocatedValue, programCurrency, maturityDays, ipaId, ipaName, depositoryId, depositoryName, isinGenerationRequestDocId, ipaVerificationRequestDocId, ipaCertificateDocId, corporateActionFormDocId, allotmentLetterDocId, status, version, lastModified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CPProgram {\n");
    
    sb.append("    programId: ").append(toIndentedString(programId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    issuerId: ").append(toIndentedString(issuerId)).append("\n");
    sb.append("    issuerName: ").append(toIndentedString(issuerName)).append("\n");
    sb.append("    issueCommencementDate: ").append(toIndentedString(issueCommencementDate)).append("\n");
    sb.append("    programSize: ").append(toIndentedString(programSize)).append("\n");
    sb.append("    programAllocatedValue: ").append(toIndentedString(programAllocatedValue)).append("\n");
    sb.append("    programCurrency: ").append(toIndentedString(programCurrency)).append("\n");
    sb.append("    maturityDays: ").append(toIndentedString(maturityDays)).append("\n");
    sb.append("    ipaId: ").append(toIndentedString(ipaId)).append("\n");
    sb.append("    ipaName: ").append(toIndentedString(ipaName)).append("\n");
    sb.append("    depositoryId: ").append(toIndentedString(depositoryId)).append("\n");
    sb.append("    depositoryName: ").append(toIndentedString(depositoryName)).append("\n");
    sb.append("    isinGenerationRequestDocId: ").append(toIndentedString(isinGenerationRequestDocId)).append("\n");
    sb.append("    ipaVerificationRequestDocId: ").append(toIndentedString(ipaVerificationRequestDocId)).append("\n");
    sb.append("    ipaCertificateDocId: ").append(toIndentedString(ipaCertificateDocId)).append("\n");
    sb.append("    corporateActionFormDocId: ").append(toIndentedString(corporateActionFormDocId)).append("\n");
    sb.append("    allotmentLetterDocId: ").append(toIndentedString(allotmentLetterDocId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

