/*
 * IndiaCP API
 * This API will drive the UI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.barclays.indiacp.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets BoardResolutionError
 */
public enum BoardResolutionError {
  
  CREATION_ERROR("BR_CREATION_ERROR"),
  
  FETCH_ERROR("BR_FETCH_ERROR"),
  
  AMENDMENT_ERROR("BR_AMENDMENT_ERROR"),
  
  CANCELLATION_ERROR("BR_CANCELLATION_ERROR"),
  
  DOES_NOT_EXIST_ERROR("BR_DOES_NOT_EXIST_ERROR"),
  
  DOC_GENERATION_ERROR("BR_DOC_GENERATION_ERROR"),
  
  DOC_UPLOAD_ERROR("BR_DOC_UPLOAD_ERROR"),
  
  HISTORY_SEARCH_ERROR("BR_HISTORY_SEARCH_ERROR");

  private String value;

  BoardResolutionError(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BoardResolutionError fromValue(String text) {
    for (BoardResolutionError b : BoardResolutionError.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

