/*
 * IndiaCP API
 * This API will drive the UI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.barclays.indiacp.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets CPIssueError
 */
public enum CPIssueError {
  
  CREATION_ERROR("CP_CREATION_ERROR"),
  
  PROGRAM_CEILING_EXCEEDED_ERROR("CP_PROGRAM_CEILING_EXCEEDED_ERROR"),
  
  FETCH_ERROR("CP_FETCH_ERROR"),
  
  DOES_NOT_EXIST_ERROR("CP_DOES_NOT_EXIST_ERROR"),
  
  AMENDMENT_ERROR("CP_AMENDMENT_ERROR"),
  
  CANCELLATION_ERROR("CP_CANCELLATION_ERROR"),
  
  DOC_GENERATION_ERROR("CP_DOC_GENERATION_ERROR"),
  
  DOC_UPLOAD_ERROR("CP_DOC_UPLOAD_ERROR"),
  
  HISTORY_SEARCH_ERROR("CP_HISTORY_SEARCH_ERROR");

  private String value;

  CPIssueError(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CPIssueError fromValue(String text) {
    for (CPIssueError b : CPIssueError.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

