/*
 * IndiaCP API
 * This API will drive the UI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.barclays.indiacp.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonValue;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets CPProgramError
 */
public enum CPProgramError {
  
  CREATION_ERROR("CP_PROGRAM_CREATION_ERROR"),
  
  CREDIT_LIMIT_EXCEEDED_ERROR("CP_PROGRAM_CREDIT_LIMIT_EXCEEDED_ERROR"),
  
  BORROWING_LIMIT_EXCEEDED_ERROR("CP_PROGRAM_BORROWING_LIMIT_EXCEEDED_ERROR"),
  
  CREDIT_RATING_VALIDITY_EXPIRED_ERROR("CP_PROGRAM_CREDIT_RATING_VALIDITY_EXPIRED_ERROR"),
  
  CANCELLATION_ERROR("CP_PROGRAM_CANCELLATION_ERROR"),
  
  FETCH_ERROR("CP_PROGRAM_FETCH_ERROR"),
  
  DOES_NOT_EXIST_ERROR("CP_PROGRAM_DOES_NOT_EXIST_ERROR"),
  
  DOC_GENERATION_ERROR("CP_PROGRAM_DOC_GENERATION_ERROR"),
  
  DOC_UPLOAD_ERROR("CP_PROGRAM_DOC_UPLOAD_ERROR"),
  
  ISIN_CREATION_ERROR("CP_PROGRAM_ISIN_CREATION_ERROR"),
  
  ISIN_ALREADY_EXISTS_ERROR("CP_PROGRAM_ISIN_ALREADY_EXISTS_ERROR"),
  
  HISTORY_SEARCH_ERROR("CP_PROGRAM_HISTORY_SEARCH_ERROR");

  private String value;

  CPProgramError(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CPProgramError fromValue(String text) {
    for (CPProgramError b : CPProgramError.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

