/*
 * IndiaCP API
 * This API will drive the UI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.barclays.indiacp.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Error
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-01-14T02:47:08.972Z")
public class Error   {
  @JsonProperty("code")
  private String code = null;

  /**
   * Source of the error identifying the layer where the error originated. For e.g. DL Integration Layer, DL (Corda/Ethereum), Reference Data Service
   */
  public enum SourceEnum {
    DL_INTEGRATION_LAYER("DL_INTEGRATION_LAYER"),
    
    DL_R3CORDA("DL_R3CORDA"),
    
    DL_ETHEREUM_QUORUM_CAKESHOP("DL_ETHEREUM_QUORUM_CAKESHOP"),
    
    DL_ETHEREUM_QUORUM("DL_ETHEREUM_QUORUM"),
    
    REFERENCE_DATA_SERVICE("REFERENCE_DATA_SERVICE"),
    
    UNKNOWN_SOURCE("UNKNOWN_SOURCE");

    private String value;

    SourceEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceEnum fromValue(String text) {
      for (SourceEnum b : SourceEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("source")
  private SourceEnum source = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("details")
  private String details = null;

  public Error code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Unique Id to identify the type of error. For e.g. CP Program Creation, ISIN Generation, etc.
   * @return code
  **/
  @JsonProperty("code")
  @ApiModelProperty(value = "Unique Id to identify the type of error. For e.g. CP Program Creation, ISIN Generation, etc.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Error source(SourceEnum source) {
    this.source = source;
    return this;
  }

   /**
   * Source of the error identifying the layer where the error originated. For e.g. DL Integration Layer, DL (Corda/Ethereum), Reference Data Service
   * @return source
  **/
  @JsonProperty("source")
  @ApiModelProperty(value = "Source of the error identifying the layer where the error originated. For e.g. DL Integration Layer, DL (Corda/Ethereum), Reference Data Service")
  public SourceEnum getSource() {
    return source;
  }

  public void setSource(SourceEnum source) {
    this.source = source;
  }

  public Error message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Short message describing the error
   * @return message
  **/
  @JsonProperty("message")
  @ApiModelProperty(value = "Short message describing the error")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public Error details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Details of the error. This could also be the complete stack trace. It would be useful for debugging
   * @return details
  **/
  @JsonProperty("details")
  @ApiModelProperty(value = "Details of the error. This could also be the complete stack trace. It would be useful for debugging")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.code, error.code) &&
        Objects.equals(this.source, error.source) &&
        Objects.equals(this.message, error.message) &&
        Objects.equals(this.details, error.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, source, message, details);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

