/*
 * IndiaCP API
 * This API will drive the UI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.barclays.indiacp.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * IndiaCPDocumentDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-01-14T02:47:08.972Z")
public class IndiaCPDocumentDetails   {
  @JsonProperty("cpProgramId")
  private String cpProgramId = null;

  @JsonProperty("cpIssueId")
  private String cpIssueId = null;

  /**
   * Type of Legal Documents exchanged and signed/countersigned by participants in the CPProgram
   */
  public enum DocTypeEnum {
    CREDIT_RATING_DOC("CREDIT_RATING_DOC"),
    
    BOARD_RESOLUTION_BORROWING_LIMIT_DOC("BOARD_RESOLUTION_BORROWING_LIMIT_DOC"),
    
    DEPOSITORY_DOCS("DEPOSITORY_DOCS"),
    
    IPA_DOCS("IPA_DOCS"),
    
    IPA_CERTIFICATE_DOC("IPA_CERTIFICATE_DOC"),
    
    CORPORATE_ACTION_FORM("CORPORATE_ACTION_FORM"),
    
    DEAL_CONFIRMATION_DOC("DEAL_CONFIRMATION_DOC");

    private String value;

    DocTypeEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DocTypeEnum fromValue(String text) {
      for (DocTypeEnum b : DocTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("docType")
  private DocTypeEnum docType = null;

  @JsonProperty("docHash")
  private String docHash = null;

  /**
   * The current status of the document. Possible values are UNSIGNED, SIGNED_BY_ISSUER, SIGNED_BY_INVESTOR, SIGNED_BY_IPA, SIGNED_BY_NSDL
   */
  public enum DocStatusEnum {
    UNKNOWN("UNKNOWN"),
    
    UNSIGNED("UNSIGNED"),
    
    SIGNED_BY_ISSUER("SIGNED_BY_ISSUER"),
    
    SIGNED_BY_INVESTOR("SIGNED_BY_INVESTOR"),
    
    SIGNED_BY_IPA("SIGNED_BY_IPA"),
    
    SIGNED_BY_NSDL("SIGNED_BY_NSDL");

    private String value;

    DocStatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DocStatusEnum fromValue(String text) {
      for (DocStatusEnum b : DocStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("docStatus")
  private DocStatusEnum docStatus = null;

  @JsonProperty("modifiedBy")
  private String modifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private Date lastModifiedDate = null;

  public IndiaCPDocumentDetails cpProgramId(String cpProgramId) {
    this.cpProgramId = cpProgramId;
    return this;
  }

   /**
   * Unique identifier of the CP Program that this document is associated with
   * @return cpProgramId
  **/
  @JsonProperty("cpProgramId")
  @ApiModelProperty(value = "Unique identifier of the CP Program that this document is associated with")
  public String getCpProgramId() {
    return cpProgramId;
  }

  public void setCpProgramId(String cpProgramId) {
    this.cpProgramId = cpProgramId;
  }

  public IndiaCPDocumentDetails cpIssueId(String cpIssueId) {
    this.cpIssueId = cpIssueId;
    return this;
  }

   /**
   * Unique identifier of the CP Issue that this document is associated with
   * @return cpIssueId
  **/
  @JsonProperty("cpIssueId")
  @ApiModelProperty(value = "Unique identifier of the CP Issue that this document is associated with")
  public String getCpIssueId() {
    return cpIssueId;
  }

  public void setCpIssueId(String cpIssueId) {
    this.cpIssueId = cpIssueId;
  }

  public IndiaCPDocumentDetails docType(DocTypeEnum docType) {
    this.docType = docType;
    return this;
  }

   /**
   * Type of Legal Documents exchanged and signed/countersigned by participants in the CPProgram
   * @return docType
  **/
  @JsonProperty("docType")
  @ApiModelProperty(value = "Type of Legal Documents exchanged and signed/countersigned by participants in the CPProgram")
  public DocTypeEnum getDocType() {
    return docType;
  }

  public void setDocType(DocTypeEnum docType) {
    this.docType = docType;
  }

  public IndiaCPDocumentDetails docHash(String docHash) {
    this.docHash = docHash;
    return this;
  }

   /**
   * SHA256 Hash of the Content of the Document. This hash uniquely identifies the document.
   * @return docHash
  **/
  @JsonProperty("docHash")
  @ApiModelProperty(value = "SHA256 Hash of the Content of the Document. This hash uniquely identifies the document.")
  public String getDocHash() {
    return docHash;
  }

  public void setDocHash(String docHash) {
    this.docHash = docHash;
  }

  public IndiaCPDocumentDetails docStatus(DocStatusEnum docStatus) {
    this.docStatus = docStatus;
    return this;
  }

   /**
   * The current status of the document. Possible values are UNSIGNED, SIGNED_BY_ISSUER, SIGNED_BY_INVESTOR, SIGNED_BY_IPA, SIGNED_BY_NSDL
   * @return docStatus
  **/
  @JsonProperty("docStatus")
  @ApiModelProperty(value = "The current status of the document. Possible values are UNSIGNED, SIGNED_BY_ISSUER, SIGNED_BY_INVESTOR, SIGNED_BY_IPA, SIGNED_BY_NSDL")
  public DocStatusEnum getDocStatus() {
    return docStatus;
  }

  public void setDocStatus(DocStatusEnum docStatus) {
    this.docStatus = docStatus;
  }

  public IndiaCPDocumentDetails modifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Unique identifier of the Logged-in User that performed the action. This is required for Audit History
   * @return modifiedBy
  **/
  @JsonProperty("modifiedBy")
  @ApiModelProperty(value = "Unique identifier of the Logged-in User that performed the action. This is required for Audit History")
  public String getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public IndiaCPDocumentDetails lastModifiedDate(Date lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Last Modified Date for this CPIssue. This is required for Audit History
   * @return lastModifiedDate
  **/
  @JsonProperty("lastModifiedDate")
  @ApiModelProperty(value = "Last Modified Date for this CPIssue. This is required for Audit History")
  public Date getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(Date lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndiaCPDocumentDetails indiaCPDocumentDetails = (IndiaCPDocumentDetails) o;
    return Objects.equals(this.cpProgramId, indiaCPDocumentDetails.cpProgramId) &&
        Objects.equals(this.cpIssueId, indiaCPDocumentDetails.cpIssueId) &&
        Objects.equals(this.docType, indiaCPDocumentDetails.docType) &&
        Objects.equals(this.docHash, indiaCPDocumentDetails.docHash) &&
        Objects.equals(this.docStatus, indiaCPDocumentDetails.docStatus) &&
        Objects.equals(this.modifiedBy, indiaCPDocumentDetails.modifiedBy) &&
        Objects.equals(this.lastModifiedDate, indiaCPDocumentDetails.lastModifiedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpProgramId, cpIssueId, docType, docHash, docStatus, modifiedBy, lastModifiedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndiaCPDocumentDetails {\n");
    
    sb.append("    cpProgramId: ").append(toIndentedString(cpProgramId)).append("\n");
    sb.append("    cpIssueId: ").append(toIndentedString(cpIssueId)).append("\n");
    sb.append("    docType: ").append(toIndentedString(docType)).append("\n");
    sb.append("    docHash: ").append(toIndentedString(docHash)).append("\n");
    sb.append("    docStatus: ").append(toIndentedString(docStatus)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

