/*
 * IndiaCP API
 * This API will drive the UI
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.barclays.indiacp.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * LegalEntityCreditRatingDocument
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-01-14T02:47:08.972Z")
public class LegalEntityCreditRatingDocument   {
  @JsonProperty("legalEntityId")
  private String legalEntityId = null;

  @JsonProperty("creditRatingAgencyName")
  private String creditRatingAgencyName = null;

  @JsonProperty("creditRatingAmount")
  private Long creditRatingAmount = null;

  @JsonProperty("currentOutstandingCreditBorrowing")
  private Long currentOutstandingCreditBorrowing = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("creditRating")
  private String creditRating = null;

  @JsonProperty("creditRatingIssuanceDate")
  private Date creditRatingIssuanceDate = null;

  @JsonProperty("creditRatingEffectiveDate")
  private Date creditRatingEffectiveDate = null;

  @JsonProperty("creditRatingExpiryDate")
  private Date creditRatingExpiryDate = null;

  @JsonProperty("docHash")
  private String docHash = null;

  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("modifiedBy")
  private String modifiedBy = null;

  @JsonProperty("lastModifiedDate")
  private Date lastModifiedDate = null;

  /**
   * There can be only one active CR Document at any given time
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    OBSOLETE("OBSOLETE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  public LegalEntityCreditRatingDocument legalEntityId(String legalEntityId) {
    this.legalEntityId = legalEntityId;
    return this;
  }

   /**
   * Unique identifier of the Legal Entity that this document is Issued for
   * @return legalEntityId
  **/
  @JsonProperty("legalEntityId")
  @ApiModelProperty(value = "Unique identifier of the Legal Entity that this document is Issued for")
  public String getLegalEntityId() {
    return legalEntityId;
  }

  public void setLegalEntityId(String legalEntityId) {
    this.legalEntityId = legalEntityId;
  }

  public LegalEntityCreditRatingDocument creditRatingAgencyName(String creditRatingAgencyName) {
    this.creditRatingAgencyName = creditRatingAgencyName;
    return this;
  }

   /**
   * The Credit Rating Agency
   * @return creditRatingAgencyName
  **/
  @JsonProperty("creditRatingAgencyName")
  @ApiModelProperty(value = "The Credit Rating Agency")
  public String getCreditRatingAgencyName() {
    return creditRatingAgencyName;
  }

  public void setCreditRatingAgencyName(String creditRatingAgencyName) {
    this.creditRatingAgencyName = creditRatingAgencyName;
  }

  public LegalEntityCreditRatingDocument creditRatingAmount(Long creditRatingAmount) {
    this.creditRatingAmount = creditRatingAmount;
    return this;
  }

   /**
   * Total Approved Borrowing Credit Limit
   * @return creditRatingAmount
  **/
  @JsonProperty("creditRatingAmount")
  @ApiModelProperty(value = "Total Approved Borrowing Credit Limit")
  public Long getCreditRatingAmount() {
    return creditRatingAmount;
  }

  public void setCreditRatingAmount(Long creditRatingAmount) {
    this.creditRatingAmount = creditRatingAmount;
  }

  public LegalEntityCreditRatingDocument currentOutstandingCreditBorrowing(Long currentOutstandingCreditBorrowing) {
    this.currentOutstandingCreditBorrowing = currentOutstandingCreditBorrowing;
    return this;
  }

   /**
   * Outstanding Credit Borrowing. This is an auto computed value. It is computed by the Smart Contract based on the outstanding open CP Program Sizes.
   * @return currentOutstandingCreditBorrowing
  **/
  @JsonProperty("currentOutstandingCreditBorrowing")
  @ApiModelProperty(value = "Outstanding Credit Borrowing. This is an auto computed value. It is computed by the Smart Contract based on the outstanding open CP Program Sizes.")
  public Long getCurrentOutstandingCreditBorrowing() {
    return currentOutstandingCreditBorrowing;
  }

  public void setCurrentOutstandingCreditBorrowing(Long currentOutstandingCreditBorrowing) {
    this.currentOutstandingCreditBorrowing = currentOutstandingCreditBorrowing;
  }

  public LegalEntityCreditRatingDocument currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency. Defaulted to INR for India Commercial Paper
   * @return currency
  **/
  @JsonProperty("currency")
  @ApiModelProperty(value = "Currency. Defaulted to INR for India Commercial Paper")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public LegalEntityCreditRatingDocument creditRating(String creditRating) {
    this.creditRating = creditRating;
    return this;
  }

   /**
   * Rating assigned by the CRA
   * @return creditRating
  **/
  @JsonProperty("creditRating")
  @ApiModelProperty(value = "Rating assigned by the CRA")
  public String getCreditRating() {
    return creditRating;
  }

  public void setCreditRating(String creditRating) {
    this.creditRating = creditRating;
  }

  public LegalEntityCreditRatingDocument creditRatingIssuanceDate(Date creditRatingIssuanceDate) {
    this.creditRatingIssuanceDate = creditRatingIssuanceDate;
    return this;
  }

   /**
   * Rating issuance date
   * @return creditRatingIssuanceDate
  **/
  @JsonProperty("creditRatingIssuanceDate")
  @ApiModelProperty(value = "Rating issuance date")
  public Date getCreditRatingIssuanceDate() {
    return creditRatingIssuanceDate;
  }

  public void setCreditRatingIssuanceDate(Date creditRatingIssuanceDate) {
    this.creditRatingIssuanceDate = creditRatingIssuanceDate;
  }

  public LegalEntityCreditRatingDocument creditRatingEffectiveDate(Date creditRatingEffectiveDate) {
    this.creditRatingEffectiveDate = creditRatingEffectiveDate;
    return this;
  }

   /**
   * Rating effective date, which can be different from the issuance date
   * @return creditRatingEffectiveDate
  **/
  @JsonProperty("creditRatingEffectiveDate")
  @ApiModelProperty(value = "Rating effective date, which can be different from the issuance date")
  public Date getCreditRatingEffectiveDate() {
    return creditRatingEffectiveDate;
  }

  public void setCreditRatingEffectiveDate(Date creditRatingEffectiveDate) {
    this.creditRatingEffectiveDate = creditRatingEffectiveDate;
  }

  public LegalEntityCreditRatingDocument creditRatingExpiryDate(Date creditRatingExpiryDate) {
    this.creditRatingExpiryDate = creditRatingExpiryDate;
    return this;
  }

   /**
   * Rating expiry date
   * @return creditRatingExpiryDate
  **/
  @JsonProperty("creditRatingExpiryDate")
  @ApiModelProperty(value = "Rating expiry date")
  public Date getCreditRatingExpiryDate() {
    return creditRatingExpiryDate;
  }

  public void setCreditRatingExpiryDate(Date creditRatingExpiryDate) {
    this.creditRatingExpiryDate = creditRatingExpiryDate;
  }

  public LegalEntityCreditRatingDocument docHash(String docHash) {
    this.docHash = docHash;
    return this;
  }

   /**
   * SHA256 Hash of the Credit Rating Document
   * @return docHash
  **/
  @JsonProperty("docHash")
  @ApiModelProperty(value = "SHA256 Hash of the Credit Rating Document")
  public String getDocHash() {
    return docHash;
  }

  public void setDocHash(String docHash) {
    this.docHash = docHash;
  }

  public LegalEntityCreditRatingDocument version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Current version of the CR Document. This is auto incremented by the DL.
   * @return version
  **/
  @JsonProperty("version")
  @ApiModelProperty(value = "Current version of the CR Document. This is auto incremented by the DL.")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public LegalEntityCreditRatingDocument modifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Unique identifier of the Logged-in User that performed the action. This is required for Audit History
   * @return modifiedBy
  **/
  @JsonProperty("modifiedBy")
  @ApiModelProperty(value = "Unique identifier of the Logged-in User that performed the action. This is required for Audit History")
  public String getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public LegalEntityCreditRatingDocument lastModifiedDate(Date lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * Last Modified Date for this CPIssue. This is required for Audit History
   * @return lastModifiedDate
  **/
  @JsonProperty("lastModifiedDate")
  @ApiModelProperty(value = "Last Modified Date for this CPIssue. This is required for Audit History")
  public Date getLastModifiedDate() {
    return lastModifiedDate;
  }

  public void setLastModifiedDate(Date lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  public LegalEntityCreditRatingDocument status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * There can be only one active CR Document at any given time
   * @return status
  **/
  @JsonProperty("status")
  @ApiModelProperty(value = "There can be only one active CR Document at any given time")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalEntityCreditRatingDocument legalEntityCreditRatingDocument = (LegalEntityCreditRatingDocument) o;
    return Objects.equals(this.legalEntityId, legalEntityCreditRatingDocument.legalEntityId) &&
        Objects.equals(this.creditRatingAgencyName, legalEntityCreditRatingDocument.creditRatingAgencyName) &&
        Objects.equals(this.creditRatingAmount, legalEntityCreditRatingDocument.creditRatingAmount) &&
        Objects.equals(this.currentOutstandingCreditBorrowing, legalEntityCreditRatingDocument.currentOutstandingCreditBorrowing) &&
        Objects.equals(this.currency, legalEntityCreditRatingDocument.currency) &&
        Objects.equals(this.creditRating, legalEntityCreditRatingDocument.creditRating) &&
        Objects.equals(this.creditRatingIssuanceDate, legalEntityCreditRatingDocument.creditRatingIssuanceDate) &&
        Objects.equals(this.creditRatingEffectiveDate, legalEntityCreditRatingDocument.creditRatingEffectiveDate) &&
        Objects.equals(this.creditRatingExpiryDate, legalEntityCreditRatingDocument.creditRatingExpiryDate) &&
        Objects.equals(this.docHash, legalEntityCreditRatingDocument.docHash) &&
        Objects.equals(this.version, legalEntityCreditRatingDocument.version) &&
        Objects.equals(this.modifiedBy, legalEntityCreditRatingDocument.modifiedBy) &&
        Objects.equals(this.lastModifiedDate, legalEntityCreditRatingDocument.lastModifiedDate) &&
        Objects.equals(this.status, legalEntityCreditRatingDocument.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(legalEntityId, creditRatingAgencyName, creditRatingAmount, currentOutstandingCreditBorrowing, currency, creditRating, creditRatingIssuanceDate, creditRatingEffectiveDate, creditRatingExpiryDate, docHash, version, modifiedBy, lastModifiedDate, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalEntityCreditRatingDocument {\n");
    
    sb.append("    legalEntityId: ").append(toIndentedString(legalEntityId)).append("\n");
    sb.append("    creditRatingAgencyName: ").append(toIndentedString(creditRatingAgencyName)).append("\n");
    sb.append("    creditRatingAmount: ").append(toIndentedString(creditRatingAmount)).append("\n");
    sb.append("    currentOutstandingCreditBorrowing: ").append(toIndentedString(currentOutstandingCreditBorrowing)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    creditRating: ").append(toIndentedString(creditRating)).append("\n");
    sb.append("    creditRatingIssuanceDate: ").append(toIndentedString(creditRatingIssuanceDate)).append("\n");
    sb.append("    creditRatingEffectiveDate: ").append(toIndentedString(creditRatingEffectiveDate)).append("\n");
    sb.append("    creditRatingExpiryDate: ").append(toIndentedString(creditRatingExpiryDate)).append("\n");
    sb.append("    docHash: ").append(toIndentedString(docHash)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

